# Generated by Django 3.0.3 on 2020-03-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=132, verbose_name='Тип объекта')),
                ('data', models.TextField(blank=True, verbose_name='Объект')),
                ('action', models.CharField(blank=True, max_length=16, verbose_name='Действие')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'История операций',
            },
        ),
    ]
