# Generated by Django 3.0.3 on 2020-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmodel',
            options={'verbose_name': 'Действие', 'verbose_name_plural': 'История действий'},
        ),
        migrations.AddField(
            model_name='logmodel',
            name='object_entry_id',
            field=models.IntegerField(default=0, verbose_name='ID объекта'),
            preserve_default=False,
        ),
    ]
