# Generated by Django 3.0.3 on 2020-03-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('cargo', '0002_auto_20200301_1804'),
        ('common', '0001_initial'),
        ('supplier', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercategory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='shipmentstock',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.Shipment'),
        ),
        migrations.AddField(
            model_name='shipmentstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Stock'),
        ),
        migrations.AddField(
            model_name='cargostock',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.Cargo'),
        ),
        migrations.AddField(
            model_name='cargostock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('supplier', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='shipmentstock',
            unique_together={('shipment', 'stock')},
        ),
        migrations.AddConstraint(
            model_name='cargostock',
            constraint=models.UniqueConstraint(fields=('cargo', 'stock'), name='cargo_stock_unique'),
        ),
    ]
