# Generated by Django 3.0.3 on 2020-02-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('common', '0002_auto_20200225_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
