# Generated by Django 3.0.2 on 2020-01-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('parent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Исполнено', 'Исполнено'), ('Проверка', 'Проверка'), ('Собрано', 'Собрано'), ('Отменено', 'Отменено')], max_length=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('qr', models.TextField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('legal_details', models.TextField()),
                ('contact_info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('article', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Исполнено', 'Исполнено'), ('В пути', 'В пути')], max_length=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Category')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Supplier')),
            ],
            options={
                'unique_together': {('supplier_id', 'category_id')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('shipment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Shipment')),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Stock')),
            ],
            options={
                'unique_together': {('shipment_id', 'stock_id')},
            },
        ),
        migrations.CreateModel(
            name='CargoStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cargo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Cargo')),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Stock')),
            ],
            options={
                'unique_together': {('cargo_id', 'stock_id')},
            },
        ),
    ]
