# Generated by Django 3.0.3 on 2020-03-01 08:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('number', models.IntegerField(verbose_name='Количество на складе')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
