# Generated by Django 3.0.2 on 2020-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='cargostock',
            old_name='cargo_id',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='cargostock',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shipmentstock',
            old_name='shipment_id',
            new_name='shipment',
        ),
        migrations.RenameField(
            model_name='shipmentstock',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='suppliercategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='suppliercategory',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='cargo',
            name='stocks',
            field=models.ManyToManyField(through='warehouse.CargoStock', to='warehouse.Stock'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='stocks',
            field=models.ManyToManyField(through='warehouse.ShipmentStock', to='warehouse.Stock'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(through='warehouse.SupplierCategory', to='warehouse.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='cargostock',
            unique_together={('cargo', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='shipmentstock',
            unique_together={('shipment', 'stock')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliercategory',
            unique_together={('supplier', 'category')},
        ),
    ]
