# Generated by Django 3.0.3 on 2020-02-29 09:47

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('common', '0003_auto_20200229_1947'),
        ('supplier', '0002_auto_20200229_1947'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
