# Generated by Django 3.0.2 on 2020-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200202_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='name',
            field=models.CharField(default='stuff', max_length=80),
        ),
        migrations.AddField(
            model_name='cargo',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
