# Generated by Django 3.0.2 on 2020-02-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_cargodetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargodetails',
            name='supplier',
        ),
    ]
