# Generated by Django 3.0.2 on 2020-02-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_cargodetails_supplier'),
        ('warehouse', '0006_auto_20200202_0103'),
    ]

    operations = [
    ]
