# Generated by Django 3.0.2 on 2020-02-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_merge_20200203_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='number',
        ),
    ]
