# Generated by Django 3.0.3 on 2020-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20200211_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='status',
            field=models.CharField(choices=[('Исполнено', 'Исполнено'), ('В пути', 'В пути')], default='В пути', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Исполнено', 'Исполнено'), ('Проверка', 'Проверка'), ('Собрано', 'Собрано'), ('Отменено', 'Отменено')], default='Проверка', max_length=9, verbose_name='Статус покупки'),
        ),
    ]
