# Generated by Django 3.0.3 on 2020-02-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20200212_1000'),
    ]

    operations = []
