# Generated by Django 3.0.3 on 2020-02-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_auto_20200216_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(blank=True, max_length=132)),
                ('data', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=16)),
            ],
        ),
    ]
