# Generated by Django 3.0.3 on 2020-02-18 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_modelchangelogsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchangelogsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
