# Generated by Django 3.0.3 on 2020-02-26 17:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_modelchangelogsmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelchangelogsmodel',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'История операций'},
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='action',
            field=models.CharField(blank=True, max_length=16, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='data',
            field=models.TextField(blank=True, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='table_name',
            field=models.CharField(blank=True, max_length=132, verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='CategoryMPTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warehouse.CategoryMPTT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.CategoryMPTT', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(through='warehouse.SupplierCategory', to='warehouse.CategoryMPTT'),
        ),
        migrations.AlterField(
            model_name='suppliercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.CategoryMPTT'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
