# Generated by Django 3.0.3 on 2020-03-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        ('common', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Исполнено', 'Исполнено'), ('Проверка', 'Проверка'), ('Собрано', 'Собрано'), ('Отменено', 'Отменено')], default='Проверка', max_length=9, verbose_name='Статус покупки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('qr', models.TextField(null=True, verbose_name='Код подтверждения')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Покупатель')),
                ('stocks', models.ManyToManyField(through='common.ShipmentStock', to='warehouse.Stock')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
